version: "3.3"

services:
  # bot:
  #   build: ./xss_ctf/bot
  #   volumes:
  #     - ./xss_ctf/bot/src:/usr/src/app
  xss:
    build: ./xss_ctf/board
    ports:
      - "10000:80"
    restart: always
    volumes:
      - ./xss_ctf/board/src:/var/www/html
  # db:
  #   image: mysql:5.6
  #   ports:
  #       - "10001:3306"
  #   environment:
  #       - MYSQL_ROOT_PASSWORD=donttouchme
  #       - MYSQL_DATABASE=testdb
  wayback:
    image: nginx:latest
    ports:
      - "10002:80"
    volumes:
      - ./wayback/src:/usr/share/nginx/html
  
 
    
    
  